### PR TITLE
Improve performance of value check

### PR DESCRIPTION
**Pull request by sdepold**
This commit fixes a degradation of performance
which was introduced in #16.

### CODE REVIEW

**Comment by mickhansen** [comment]
Thanks @sdepold

**Comment by joepie91** [comment]
Looks like a minor performance increase can be had by weakly checking for `null` (which matches `null` and `undefined`): https://jsperf.com/undefined-null-check/2

**Comment by mickhansen** [comment]
@joepie91 PR welcome.

**Comment by mickhansen** [comment]
Looks like a very minor difference though

**Pull request merged**
