### PR TITLE
chore: update code, reduce package size

### LINKED ISSUE #30: Add license to NPM
:wave: Hello, could you please update NPM with the license (MIT) for this project?

https://www.npmjs.com/package/dottie

It it currently reflecting as `none`, despite your GitHub license, README.md and LICENSE stating that it is MIT licensed.  

dottie_-_npm

Thank you!

### LINKED ISSUE #31: Exclude redundant files from publish to reduce package size
travis, tests, etc.

### PR DESCRIPTION
**Pull request by SimonSchick**
Fixes #30
Fixes #31

Changes:
  - Removed 0.12 from CI in favor of 6, 8 and 10 (0.12 still works)
  - Removed some dead code (clone)
  - Updated dev dependencies to latest dependencies or their modern equivalents.
  - Only publish `dottie.js`
  - Added license to NPM

### CODE REVIEW

**Comment by SimonSchick** [comment]
@mickhansen ping due to github outage, making sure you get this.

**Comment by SimonSchick** [comment]
Any reason you don't want the lockfile?
I know npm used to handle them really badly, but that's not really the case anymore :P
Anyhow, given the small size I will remove it for you.

**Comment by mickhansen** [comment]
Some people use yarn etc

**Comment by SimonSchick** [comment]
@janmeier one advantage that I observed is that they tend to prevent build failures in case packages are released in violation of semver, this applies to end user projects and libraries.

**Comment by janmeier** [comment]
One argument I've heard is that you actually want to find semver breaking dependencies in libaries, so you know about them before the consumers of your library (those not using lockfiles).
I'm googling really hard, but having a hard time finding any sources for that though :D

**Comment by janmeier** [comment]
https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/ Appearently publishing yarn lockfiles is fine, since yarn will ignore nested lockfiles - not sure about NPM

**Pull request merged**
